import z from "zod";

export const templateSchema = z.enum([
	"azurill",
	"bronzor",
	"collection001",
	"collection002",
	"collection003",
	"collection005",
	"collection007",
	"collection016",
	"collection017",
	"collection018",
	"collection019",
	"collection020",
	"collection021",
	"collection022",
	"collection024",
	"collection026",
	"collection027",
	"collection028",
	"collection029",
	"chikorita",
	"ditgar",
	"ditto",
	"gengar",
	"glalie",
	"kakuna",
	"lapras",
	"leafish",
	"meowth",
	"onyx",
	"pikachu",
	"rhyhorn",
	"scizor",
]);

export type Template = z.infer<typeof templateSchema>;
