import type { MessageDescriptor } from "@lingui/core";
import type { Template } from "@reactive-resume/schema/templates";
import { msg } from "@lingui/core/macro";

export type TemplateMetadata = {
	name: string;
	description: MessageDescriptor;
	imageUrl: string;
	accentColor?: string;
	tags: string[];
	sidebarPosition: "left" | "right" | "none";
};

export type CollectionTemplateReference = {
	id: string;
	name: string;
	description: string;
	imageUrl: string;
	tags: string[];
	baseTemplate: Template;
	accentColor: string;
	sidebarPosition: "left" | "right" | "none";
	review: "上线推荐" | "可参考" | "待重做";
};

export const templates = {
	azurill: {
		name: "标准双栏",
		description: msg`适合产品、技术和通用岗位，左侧放辅助信息，右侧突出总结、经历和项目成果。`,
		imageUrl: "/templates/jpg/azurill.jpg",
		accentColor: "rgba(31, 58, 95, 1)",
		tags: ["双栏", "中文投递", "产品", "技术岗"],
		sidebarPosition: "left",
	},
	bronzor: {
		name: "企业简洁",
		description: msg`克制、稳重、信息密度适中，适合金融、咨询、运营和传统企业岗位。`,
		imageUrl: "/templates/jpg/bronzor.jpg",
		accentColor: "rgba(111, 94, 74, 1)",
		tags: ["简洁", "专业", "金融", "咨询"],
		sidebarPosition: "none",
	},
	chikorita: {
		name: "柔和双栏",
		description: msg`更温和的双栏结构，适合市场、人力资源、客户成功和面向业务的岗位。`,
		imageUrl: "/templates/jpg/chikorita.jpg",
		tags: ["双栏", "市场", "人力资源", "客户成功"],
		sidebarPosition: "right",
	},
	ditgar: {
		name: "深色技术",
		description: msg`深色侧栏承载技能和联系方式，主体保留清晰经历，适合开发者、数据和技术产品岗位。`,
		imageUrl: "/templates/jpg/ditgar.jpg",
		tags: ["双栏", "开发者", "数据", "深色侧栏"],
		sidebarPosition: "left",
	},
	ditto: {
		name: "ATS 极简",
		description: msg`少装饰、强可读，适合网申系统、校招和需要高兼容性的中文简历。`,
		imageUrl: "/templates/jpg/ditto.jpg",
		accentColor: "rgba(38, 43, 51, 1)",
		tags: ["ATS 友好", "极简", "校招", "信息密集"],
		sidebarPosition: "none",
	},
	gengar: {
		name: "商务均衡",
		description: msg`版面均衡，适合商业分析、运营增长、项目管理等需要成果叙述的岗位。`,
		imageUrl: "/templates/jpg/gengar.jpg",
		tags: ["商务", "运营", "商业分析", "项目管理"],
		sidebarPosition: "left",
	},
	glalie: {
		name: "克制灰栏",
		description: msg`灰色侧栏弱化装饰感，适合法务、财务、管理层和更正式的投递场景。`,
		imageUrl: "/templates/jpg/glalie.jpg",
		tags: ["专业", "财务", "法务", "管理层"],
		sidebarPosition: "left",
	},
	kakuna: {
		name: "实习紧凑",
		description: msg`单栏紧凑排版，适合实习、初级岗位和经历较少但需要重点突出的候选人。`,
		imageUrl: "/templates/jpg/kakuna.jpg",
		tags: ["单栏", "实习", "初级岗位", "紧凑"],
		sidebarPosition: "none",
	},
	lapras: {
		name: "资深单栏",
		description: msg`严肃的一页单栏结构，适合资深工程师、负责人和企业级岗位投递。`,
		imageUrl: "/templates/jpg/lapras.jpg",
		accentColor: "rgba(49, 65, 85, 1)",
		tags: ["单栏", "资深", "企业级", "技术负责人"],
		sidebarPosition: "none",
	},
	leafish: {
		name: "自然侧栏",
		description: msg`色彩更柔和，适合品牌市场、公益、医疗健康和可持续发展相关岗位。`,
		imageUrl: "/templates/jpg/leafish.jpg",
		tags: ["双栏", "品牌", "公益", "医疗健康"],
		sidebarPosition: "right",
	},
	meowth: {
		name: "亚洲精简",
		description: msg`行内标题更贴近中日韩简历习惯，适合希望保持简洁和高信息密度的候选人。`,
		imageUrl: "/templates/jpg/meowth.jpg",
		tags: ["单栏", "亚洲风格", "ATS 友好", "紧凑"],
		sidebarPosition: "none",
	},
	onyx: {
		name: "通用一页",
		description: msg`通用的一页式结构，适合技术、产品、运营和职能岗位的日常版本维护。`,
		imageUrl: "/templates/jpg/onyx.jpg",
		accentColor: "rgba(35, 43, 55, 1)",
		tags: ["单栏", "通用", "一页版", "专业"],
		sidebarPosition: "none",
	},
	pikachu: {
		name: "轻量创意",
		description: msg`保留轻量强调色，适合内容、编辑、设计和更年轻的投递场景。`,
		imageUrl: "/templates/jpg/pikachu.jpg",
		tags: ["双栏", "创意", "内容", "设计"],
		sidebarPosition: "left",
	},
	rhyhorn: {
		name: "留白设计",
		description: msg`更大留白和清爽页眉，适合设计师、内容创作者和作品集型简历。`,
		imageUrl: "/templates/jpg/rhyhorn.jpg",
		tags: ["单栏", "留白", "设计师", "作品集"],
		sidebarPosition: "none",
	},
	scizor: {
		name: "高管咨询",
		description: msg`标题强调更明确，适合咨询、高管、创业公司和需要强成果表达的候选人。`,
		imageUrl: "/templates/jpg/scizor.jpg",
		accentColor: "rgba(132, 93, 55, 1)",
		tags: ["单栏", "咨询", "管理层", "成果导向"],
		sidebarPosition: "none",
	},
} as const satisfies Record<Template, TemplateMetadata>;

export const featuredTemplateIds = [
	"onyx",
	"bronzor",
	"azurill",
	"ditto",
	"lapras",
	"scizor",
] as const satisfies Template[];

export const primaryTemplateIds = featuredTemplateIds;

export const onlineStyleTemplateReferences = [
	{
		id: "online-tech-sidebar",
		name: "技术侧栏",
		description: "深绿色侧栏突出技能和联系方式，适合前端、后端、数据和工程岗位。",
		imageUrl: "/templates/online/resumify-tech-sidebar.svg",
		tags: ["技术", "侧栏", "工程"],
		baseTemplate: "azurill",
		accentColor: "rgba(15, 118, 110, 1)",
		sidebarPosition: "left",
		review: "上线推荐",
	},
	{
		id: "online-modern-minimal",
		name: "现代极简",
		description: "留白克制、信息层级清楚，适合通用投递、产品和运营岗位。",
		imageUrl: "/templates/online/resumify-modern-minimal.svg",
		tags: ["极简", "通用", "ATS"],
		baseTemplate: "onyx",
		accentColor: "rgba(31, 58, 95, 1)",
		sidebarPosition: "none",
		review: "上线推荐",
	},
	{
		id: "online-business",
		name: "商务简洁",
		description: "商务感更强，适合咨询、金融、产品经理和项目管理岗位。",
		imageUrl: "/templates/online/resumify-business.svg",
		tags: ["商务", "咨询", "管理"],
		baseTemplate: "bronzor",
		accentColor: "rgba(92, 83, 69, 1)",
		sidebarPosition: "none",
		review: "上线推荐",
	},
	{
		id: "online-elegant-timeline",
		name: "优雅时间轴",
		description: "时间线更突出，适合经历完整、项目跨度较长的候选人。",
		imageUrl: "/templates/online/resumify-elegant-timeline.svg",
		tags: ["时间轴", "经历", "资深"],
		baseTemplate: "lapras",
		accentColor: "rgba(62, 92, 118, 1)",
		sidebarPosition: "none",
		review: "上线推荐",
	},
	{
		id: "online-ats-dense",
		name: "中文 ATS 紧凑",
		description: "单页信息密度高，适合网申、校招和需要机器解析的中文简历。",
		imageUrl: "/templates/online/cn-ats-dense.svg",
		tags: ["ATS", "紧凑", "校招"],
		baseTemplate: "ditto",
		accentColor: "rgba(21, 94, 117, 1)",
		sidebarPosition: "none",
		review: "上线推荐",
	},
	{
		id: "online-cn-hr-clean",
		name: "HR 清爽",
		description: "结构柔和，适合人力资源、行政、客户成功和职能岗位。",
		imageUrl: "/templates/online/cn-hr-clean.svg",
		tags: ["职能", "清爽", "HR"],
		baseTemplate: "chikorita",
		accentColor: "rgba(69, 132, 108, 1)",
		sidebarPosition: "right",
		review: "上线推荐",
	},
	{
		id: "online-creative",
		name: "轻创意",
		description: "保留创意感但不过度装饰，适合内容、设计、品牌和新媒体岗位。",
		imageUrl: "/templates/online/resumify-creative.svg",
		tags: ["创意", "内容", "设计"],
		baseTemplate: "pikachu",
		accentColor: "rgba(185, 92, 75, 1)",
		sidebarPosition: "left",
		review: "上线推荐",
	},
	{
		id: "online-apache-timeline",
		name: "开源时间线",
		description: "参考开源时间线排版，适合项目经历清晰、需要突出成长路径的候选人。",
		imageUrl: "/templates/online/apache-timeline.svg",
		tags: ["开源", "时间线", "项目"],
		baseTemplate: "gengar",
		accentColor: "rgba(44, 95, 130, 1)",
		sidebarPosition: "left",
		review: "上线推荐",
	},
] as const satisfies CollectionTemplateReference[];

export const collectionTemplateReferences = [
	{
		id: "collection-001",
		name: "001 蓝色时间轴",
		description: "蓝色标题条和清晰时间轴，适合技术、产品和运营岗位的稳重投递。",
		imageUrl: "/templates/collection/001.jpg",
		tags: ["蓝色", "时间轴", "单栏"],
		baseTemplate: "onyx",
		accentColor: "rgba(67, 105, 145, 1)",
		sidebarPosition: "none",
		review: "上线推荐",
	},
	{
		id: "collection-002",
		name: "002 金色商务",
		description: "金色分隔和集中页眉，适合商务、咨询、产品和管理岗位。",
		imageUrl: "/templates/collection/002.jpg",
		tags: ["金色", "商务", "单栏"],
		baseTemplate: "scizor",
		accentColor: "rgba(179, 132, 57, 1)",
		sidebarPosition: "none",
		review: "上线推荐",
	},
	{
		id: "collection-003",
		name: "003 深蓝横栏",
		description: "强横栏结构，信息密度高，适合网申和需要突出经历的候选人。",
		imageUrl: "/templates/collection/003.jpg",
		tags: ["深蓝", "信息密集", "单栏"],
		baseTemplate: "ditto",
		accentColor: "rgba(34, 70, 101, 1)",
		sidebarPosition: "none",
		review: "上线推荐",
	},
	{
		id: "collection-004",
		name: "004 红色侧栏",
		description: "红色头像侧栏和右侧时间轴，适合运营、市场和内容岗位。",
		imageUrl: "/templates/collection/004.jpg",
		tags: ["红色", "侧栏", "时间轴"],
		baseTemplate: "azurill",
		accentColor: "rgba(220, 83, 84, 1)",
		sidebarPosition: "left",
		review: "可参考",
	},
	{
		id: "collection-005",
		name: "005 深蓝侧栏",
		description: "深色侧栏承载联系方式，主体较克制，适合技术和项目管理岗位。",
		imageUrl: "/templates/collection/005.jpg",
		tags: ["深蓝", "侧栏", "技术岗"],
		baseTemplate: "azurill",
		accentColor: "rgba(50, 78, 102, 1)",
		sidebarPosition: "left",
		review: "上线推荐",
	},
	{
		id: "collection-006",
		name: "006 蓝色几何",
		description: "顶部几何块较强，适合年轻化岗位，正式投递前需要克制处理。",
		imageUrl: "/templates/collection/006.jpg",
		tags: ["蓝色", "几何", "双栏"],
		baseTemplate: "azurill",
		accentColor: "rgba(76, 154, 198, 1)",
		sidebarPosition: "right",
		review: "可参考",
	},
	{
		id: "collection-007",
		name: "007 深灰蓝栏",
		description: "左侧深灰信息栏和蓝色节点，适合技术、数据和设计岗位。",
		imageUrl: "/templates/collection/007.jpg",
		tags: ["深灰", "蓝色", "侧栏"],
		baseTemplate: "azurill",
		accentColor: "rgba(30, 145, 190, 1)",
		sidebarPosition: "left",
		review: "可参考",
	},
	{
		id: "collection-014",
		name: "014 彩色技能栏",
		description: "多色技能条视觉明显，更适合作为创意岗位参考，不建议直接大量使用。",
		imageUrl: "/templates/collection/014.jpg",
		tags: ["彩色", "技能条", "创意"],
		baseTemplate: "azurill",
		accentColor: "rgba(97, 175, 46, 1)",
		sidebarPosition: "left",
		review: "待重做",
	},
	{
		id: "collection-016",
		name: "016 浅蓝双栏",
		description: "浅蓝侧栏和右侧经历时间线，适合实习、校招和初级岗位。",
		imageUrl: "/templates/collection/016.jpg",
		tags: ["浅蓝", "双栏", "校招"],
		baseTemplate: "azurill",
		accentColor: "rgba(79, 153, 207, 1)",
		sidebarPosition: "left",
		review: "上线推荐",
	},
	{
		id: "collection-017",
		name: "017 绿色侧栏",
		description: "绿色模块层级清楚，适合运营、行政、职能和业务岗位。",
		imageUrl: "/templates/collection/017.jpg",
		tags: ["绿色", "侧栏", "职能"],
		baseTemplate: "azurill",
		accentColor: "rgba(88, 165, 62, 1)",
		sidebarPosition: "left",
		review: "可参考",
	},
	{
		id: "collection-018",
		name: "018 灰色信息栏",
		description: "灰色信息栏较稳重，适合财务、行政、法务和传统行业岗位。",
		imageUrl: "/templates/collection/018.jpg",
		tags: ["灰色", "侧栏", "稳重"],
		baseTemplate: "azurill",
		accentColor: "rgba(82, 91, 102, 1)",
		sidebarPosition: "left",
		review: "可参考",
	},
	{
		id: "collection-019",
		name: "019 蓝色块面",
		description: "蓝色块面更像传统招聘模板，适合信息完整但需要弱化装饰。",
		imageUrl: "/templates/collection/019.jpg",
		tags: ["蓝色", "块面", "传统"],
		baseTemplate: "azurill",
		accentColor: "rgba(75, 147, 190, 1)",
		sidebarPosition: "right",
		review: "可参考",
	},
	{
		id: "collection-020",
		name: "020 青蓝侧栏",
		description: "青蓝侧栏和图标分区清晰，适合技术、数据和工程岗位。",
		imageUrl: "/templates/collection/020.jpg",
		tags: ["青蓝", "侧栏", "工程"],
		baseTemplate: "azurill",
		accentColor: "rgba(42, 151, 188, 1)",
		sidebarPosition: "left",
		review: "上线推荐",
	},
	{
		id: "collection-021",
		name: "021 蓝色标签",
		description: "横向标签结构清楚，适合需要突出模块标题的通用简历。",
		imageUrl: "/templates/collection/021.jpg",
		tags: ["蓝色", "标签", "单栏"],
		baseTemplate: "lapras",
		accentColor: "rgba(57, 101, 167, 1)",
		sidebarPosition: "none",
		review: "上线推荐",
	},
	{
		id: "collection-022",
		name: "022 绿色时间轴",
		description: "绿色时间线和侧栏组合，适合运营、市场和职能类简历。",
		imageUrl: "/templates/collection/022.jpg",
		tags: ["绿色", "时间轴", "侧栏"],
		baseTemplate: "azurill",
		accentColor: "rgba(48, 177, 89, 1)",
		sidebarPosition: "left",
		review: "可参考",
	},
	{
		id: "collection-023",
		name: "023 淡雅花纹",
		description: "淡色背景和花纹更偏个人化，适合轻量参考，不适合严肃投递直接使用。",
		imageUrl: "/templates/collection/023.jpg",
		tags: ["淡色", "花纹", "个人化"],
		baseTemplate: "scizor",
		accentColor: "rgba(125, 164, 190, 1)",
		sidebarPosition: "none",
		review: "待重做",
	},
	{
		id: "collection-024",
		name: "024 蓝色边框",
		description: "蓝色边框和左右分区清晰，适合校招、技术和通用岗位。",
		imageUrl: "/templates/collection/024.jpg",
		tags: ["蓝色", "边框", "双栏"],
		baseTemplate: "azurill",
		accentColor: "rgba(47, 132, 189, 1)",
		sidebarPosition: "left",
		review: "上线推荐",
	},
	{
		id: "collection-026",
		name: "026 深灰橙色",
		description: "深灰侧栏配橙色强调，适合设计、内容和运营岗位参考。",
		imageUrl: "/templates/collection/026.jpg",
		tags: ["深灰", "橙色", "侧栏"],
		baseTemplate: "azurill",
		accentColor: "rgba(232, 137, 43, 1)",
		sidebarPosition: "left",
		review: "可参考",
	},
	{
		id: "collection-027",
		name: "027 绿色横栏",
		description: "绿色横栏较传统但层级明确，适合单页通用投递。",
		imageUrl: "/templates/collection/027.jpg",
		tags: ["绿色", "横栏", "单栏"],
		baseTemplate: "onyx",
		accentColor: "rgba(80, 180, 107, 1)",
		sidebarPosition: "none",
		review: "可参考",
	},
	{
		id: "collection-028",
		name: "028 蓝色二维码栏",
		description: "带二维码和头像栏，适合有作品集入口的设计、技术和内容岗位。",
		imageUrl: "/templates/collection/028.jpg",
		tags: ["蓝色", "二维码", "侧栏"],
		baseTemplate: "azurill",
		accentColor: "rgba(76, 139, 191, 1)",
		sidebarPosition: "left",
		review: "可参考",
	},
	{
		id: "collection-029",
		name: "029 细蓝侧栏",
		description: "细蓝侧栏和项目分区明显，适合技术和项目型简历。",
		imageUrl: "/templates/collection/029.jpg",
		tags: ["蓝色", "侧栏", "项目"],
		baseTemplate: "azurill",
		accentColor: "rgba(40, 150, 215, 1)",
		sidebarPosition: "left",
		review: "可参考",
	},
	{
		id: "collection-030",
		name: "030 蓝色技能栏",
		description: "技能条和双栏布局明显，适合技能展示，但投递版需要降低装饰强度。",
		imageUrl: "/templates/collection/030.jpg",
		tags: ["蓝色", "技能条", "双栏"],
		baseTemplate: "azurill",
		accentColor: "rgba(52, 162, 205, 1)",
		sidebarPosition: "right",
		review: "待重做",
	},
	{
		id: "collection-031",
		name: "031 青绿色节点",
		description: "青绿色头部和圆形节点更年轻，适合创意、内容和运营岗位参考。",
		imageUrl: "/templates/collection/031.jpg",
		tags: ["青绿", "节点", "创意"],
		baseTemplate: "azurill",
		accentColor: "rgba(60, 194, 186, 1)",
		sidebarPosition: "left",
		review: "待重做",
	},
	{
		id: "collection-036",
		name: "036 深色技能圈",
		description: "深色侧栏和技能圆环视觉强，适合参考，不建议作为严肃投递默认模板。",
		imageUrl: "/templates/collection/036.jpg",
		tags: ["深色", "技能圈", "侧栏"],
		baseTemplate: "azurill",
		accentColor: "rgba(48, 80, 110, 1)",
		sidebarPosition: "left",
		review: "待重做",
	},
] as const satisfies CollectionTemplateReference[];

export const recommendedCollectionTemplateReferences = collectionTemplateReferences.filter(
	(reference) => reference.review === "上线推荐",
);

export const additionalCollectionTemplateReferences = collectionTemplateReferences.filter(
	(reference) => reference.review === "可参考",
);

export const deferredCollectionTemplateReferences = collectionTemplateReferences.filter(
	(reference) => reference.review === "待重做",
);
