import type { MessageDescriptor } from "@lingui/core";
import type { Template } from "@reactive-resume/schema/templates";
import { msg } from "@lingui/core/macro";

export type TemplateMetadata = {
	name: string;
	audience: string;
	description: MessageDescriptor;
	imageUrl: string;
	accentColor?: string;
	tags: string[];
	sidebarPosition: "left" | "right" | "none";
};

export const templates = {
	azurill: {
		name: "标准双栏",
		audience: "适合产品、技术和通用岗位",
		description: msg`适合产品、技术和通用岗位，左侧放辅助信息，右侧突出总结、经历和项目成果。`,
		imageUrl: "/templates/jpg/azurill.jpg",
		accentColor: "rgba(31, 58, 95, 1)",
		tags: ["双栏", "成果叙述", "侧栏信息", "通用"],
		sidebarPosition: "left",
	},
	bronzor: {
		name: "企业简洁",
		audience: "适合金融、咨询、运营和传统企业岗位",
		description: msg`克制、稳重、信息密度适中，适合金融、咨询、运营和传统企业岗位。`,
		imageUrl: "/templates/jpg/bronzor.jpg",
		accentColor: "rgba(111, 94, 74, 1)",
		tags: ["单栏", "稳重", "专业", "信息适中"],
		sidebarPosition: "none",
	},
	collection001: {
		name: "蓝色时间轴",
		audience: "适合技术、产品、运营的稳重一页投递",
		description: msg`参考传统中文招聘模板的蓝绿色分隔与时间轴结构，适合技术、产品和运营岗位的一页投递。`,
		imageUrl: "/templates/collection/001.jpg",
		accentColor: "rgba(47, 111, 122, 1)",
		tags: ["时间轴", "稳重", "单栏", "蓝绿色"],
		sidebarPosition: "none",
	},
	collection002: {
		name: "金色商务",
		audience: "适合商务、咨询、金融和管理岗位",
		description: msg`用金色标题线和稳重单栏结构承载经历，适合商务、咨询、金融和管理岗位。`,
		imageUrl: "/templates/collection/002.jpg",
		accentColor: "rgba(185, 138, 59, 1)",
		tags: ["商务", "金色标题", "单栏", "正式"],
		sidebarPosition: "none",
	},
	collection003: {
		name: "深蓝横栏",
		audience: "适合需要头像、联系方式和清晰时间轴的候选人",
		description: msg`深蓝横向信息栏配合时间轴正文，适合需要头像、联系方式和清晰经历顺序的中文简历。`,
		imageUrl: "/templates/collection/003.jpg",
		accentColor: "rgba(40, 82, 111, 1)",
		tags: ["横栏", "深蓝", "时间轴", "信息密集"],
		sidebarPosition: "none",
	},
	collection005: {
		name: "深蓝侧栏",
		audience: "适合技术、项目和数据岗位",
		description: msg`深色左侧栏突出个人信息与技能，右侧保留清晰经历区块，适合技术、项目和数据岗位。`,
		imageUrl: "/templates/collection/005.jpg",
		accentColor: "rgba(49, 93, 125, 1)",
		tags: ["侧栏", "技术岗", "深蓝", "项目"],
		sidebarPosition: "left",
	},
	collection007: {
		name: "深灰蓝栏",
		audience: "适合技术、数据、设计和项目型简历",
		description: msg`深灰信息栏搭配蓝色模块标题，信息密度高，适合技术、数据、设计和项目型中文简历。`,
		imageUrl: "/templates/collection/007.jpg",
		accentColor: "rgba(30, 145, 190, 1)",
		tags: ["侧栏", "高密度", "深灰蓝", "项目"],
		sidebarPosition: "left",
	},
	collection016: {
		name: "浅蓝双栏",
		audience: "适合校招、实习、初级岗位和信息完整简历",
		description: msg`浅蓝信息栏配合右侧经历时间线，适合校招、实习、初级岗位和信息完整的中文简历。`,
		imageUrl: "/templates/collection/016.jpg",
		accentColor: "rgba(79, 153, 207, 1)",
		tags: ["校招", "浅蓝", "双栏", "时间线"],
		sidebarPosition: "left",
	},
	collection017: {
		name: "绿色侧栏",
		audience: "适合运营、行政、职能和业务支持岗位",
		description: msg`绿色模块层级清楚，视觉温和但不空，适合运营、行政、职能和业务支持岗位。`,
		imageUrl: "/templates/collection/017.jpg",
		accentColor: "rgba(88, 165, 62, 1)",
		tags: ["职能", "绿色", "侧栏", "温和"],
		sidebarPosition: "left",
	},
	collection018: {
		name: "灰色信息栏",
		audience: "适合财务、法务、行政等正式场景",
		description: msg`灰色信息栏更克制稳重，适合财务、行政、法务、传统行业和正式投递场景。`,
		imageUrl: "/templates/collection/018.jpg",
		accentColor: "rgba(82, 91, 102, 1)",
		tags: ["正式", "灰色", "稳重", "侧栏"],
		sidebarPosition: "left",
	},
	collection019: {
		name: "蓝色块面",
		audience: "适合校招、职能和传统行业投递",
		description: msg`蓝色块面和传统信息区更接近常见中文招聘模板，适合校招、职能和传统行业投递。`,
		imageUrl: "/templates/collection/019.jpg",
		accentColor: "rgba(75, 147, 190, 1)",
		tags: ["传统", "块面", "蓝色", "右侧栏"],
		sidebarPosition: "right",
	},
	collection020: {
		name: "青蓝侧栏",
		audience: "适合技术、数据和工程岗位",
		description: msg`青蓝侧栏和清晰分区适合技术、数据和工程岗位，能突出技能与项目经历。`,
		imageUrl: "/templates/collection/020.jpg",
		accentColor: "rgba(42, 151, 188, 1)",
		tags: ["工程", "青蓝", "侧栏", "技能突出"],
		sidebarPosition: "left",
	},
	collection021: {
		name: "蓝色标签",
		audience: "适合产品、运营、职能和通用中文简历",
		description: msg`横向标签式标题让模块层次更清楚，适合产品、运营、职能和通用中文简历。`,
		imageUrl: "/templates/collection/021.jpg",
		accentColor: "rgba(57, 101, 167, 1)",
		tags: ["通用", "标签标题", "单栏", "模块清晰"],
		sidebarPosition: "none",
	},
	collection022: {
		name: "绿色时间轴",
		audience: "适合运营、市场、职能和成长路径清晰候选人",
		description: msg`绿色时间线和侧栏组合，模块区分清楚，适合运营、市场、职能和成长路径明确的候选人。`,
		imageUrl: "/templates/collection/022.jpg",
		accentColor: "rgba(48, 177, 89, 1)",
		tags: ["时间轴", "绿色", "侧栏", "成长路径"],
		sidebarPosition: "left",
	},
	collection024: {
		name: "蓝色边框",
		audience: "适合校招、技术和通用岗位",
		description: msg`蓝色边框和左右分区更接近传统中文招聘模板，适合校招、技术和通用岗位。`,
		imageUrl: "/templates/collection/024.jpg",
		accentColor: "rgba(47, 132, 189, 1)",
		tags: ["双栏", "边框", "蓝色", "传统"],
		sidebarPosition: "left",
	},
	collection026: {
		name: "深灰橙色",
		audience: "适合项目型、设计型和技术型中文简历",
		description: msg`深灰侧栏配橙色强调，信息层级强，适合项目型、设计型和技术型中文简历。`,
		imageUrl: "/templates/collection/026.jpg",
		accentColor: "rgba(232, 137, 43, 1)",
		tags: ["设计感", "深灰橙", "侧栏", "层级强"],
		sidebarPosition: "left",
	},
	collection027: {
		name: "绿色横栏",
		audience: "适合网申、校招和一页高密度通用投递",
		description: msg`绿色横栏较传统但层级明确，适合网申、校招和需要一页高密度展示的通用投递。`,
		imageUrl: "/templates/collection/027.jpg",
		accentColor: "rgba(80, 180, 107, 1)",
		tags: ["网申", "绿色横栏", "单栏", "高密度"],
		sidebarPosition: "none",
	},
	collection028: {
		name: "蓝色二维码栏",
		audience: "适合带项目链接或作品集入口的候选人",
		description: msg`蓝色侧栏适合放头像、联系方式和作品入口，适合有项目链接或作品集的候选人。`,
		imageUrl: "/templates/collection/028.jpg",
		accentColor: "rgba(76, 139, 191, 1)",
		tags: ["作品集", "二维码栏", "蓝色", "侧栏"],
		sidebarPosition: "left",
	},
	collection029: {
		name: "细蓝侧栏",
		audience: "适合技术、项目、工程和作品入口展示",
		description: msg`细蓝侧栏和项目分区明显，适合技术、项目、工程和需要展示作品入口的候选人。`,
		imageUrl: "/templates/collection/029.jpg",
		accentColor: "rgba(40, 150, 215, 1)",
		tags: ["项目型", "细蓝侧栏", "工程", "作品入口"],
		sidebarPosition: "left",
	},
	chikorita: {
		name: "柔和双栏",
		audience: "适合市场、人力资源、客户成功和业务岗位",
		description: msg`更温和的双栏结构，适合市场、人力资源、客户成功和面向业务的岗位。`,
		imageUrl: "/templates/jpg/chikorita.jpg",
		tags: ["双栏", "市场", "人力资源", "客户成功"],
		sidebarPosition: "right",
	},
	ditgar: {
		name: "深色技术",
		audience: "适合开发者、数据和技术产品岗位",
		description: msg`深色侧栏承载技能和联系方式，主体保留清晰经历，适合开发者、数据和技术产品岗位。`,
		imageUrl: "/templates/jpg/ditgar.jpg",
		tags: ["双栏", "开发者", "数据", "深色侧栏"],
		sidebarPosition: "left",
	},
	ditto: {
		name: "ATS 极简",
		audience: "适合网申系统、校招和高兼容中文简历",
		description: msg`少装饰、强可读，适合网申系统、校招和需要高兼容性的中文简历。`,
		imageUrl: "/templates/jpg/ditto.jpg",
		accentColor: "rgba(38, 43, 51, 1)",
		tags: ["ATS 友好", "极简", "校招", "信息密集"],
		sidebarPosition: "none",
	},
	gengar: {
		name: "商务均衡",
		audience: "适合商业分析、运营增长和项目管理",
		description: msg`版面均衡，适合商业分析、运营增长、项目管理等需要成果叙述的岗位。`,
		imageUrl: "/templates/jpg/gengar.jpg",
		tags: ["商务", "运营", "商业分析", "项目管理"],
		sidebarPosition: "left",
	},
	glalie: {
		name: "克制灰栏",
		audience: "适合法务、财务、管理层和正式投递",
		description: msg`灰色侧栏弱化装饰感，适合法务、财务、管理层和更正式的投递场景。`,
		imageUrl: "/templates/jpg/glalie.jpg",
		tags: ["专业", "财务", "法务", "管理层"],
		sidebarPosition: "left",
	},
	kakuna: {
		name: "实习紧凑",
		audience: "适合实习、初级岗位和经历较少候选人",
		description: msg`单栏紧凑排版，适合实习、初级岗位和经历较少但需要重点突出的候选人。`,
		imageUrl: "/templates/jpg/kakuna.jpg",
		accentColor: "rgba(37, 99, 235, 1)",
		tags: ["单栏", "实习", "初级岗位", "紧凑"],
		sidebarPosition: "none",
	},
	lapras: {
		name: "资深单栏",
		audience: "适合资深工程师、负责人和企业级岗位",
		description: msg`严肃的一页单栏结构，适合资深工程师、负责人和企业级岗位投递。`,
		imageUrl: "/templates/jpg/lapras.jpg",
		accentColor: "rgba(49, 65, 85, 1)",
		tags: ["单栏", "资深", "企业级", "技术负责人"],
		sidebarPosition: "none",
	},
	leafish: {
		name: "自然侧栏",
		audience: "适合品牌市场、公益、医疗健康和可持续岗位",
		description: msg`色彩更柔和，适合品牌市场、公益、医疗健康和可持续发展相关岗位。`,
		imageUrl: "/templates/jpg/leafish.jpg",
		tags: ["双栏", "品牌", "公益", "医疗健康"],
		sidebarPosition: "right",
	},
	meowth: {
		name: "亚洲精简",
		audience: "适合偏中日韩风格的高密度投递",
		description: msg`行内标题更贴近中日韩简历习惯，适合希望保持简洁和高信息密度的候选人。`,
		imageUrl: "/templates/jpg/meowth.jpg",
		accentColor: "rgba(37, 99, 235, 1)",
		tags: ["单栏", "亚洲风格", "ATS 友好", "紧凑"],
		sidebarPosition: "none",
	},
	onyx: {
		name: "通用一页",
		audience: "适合技术、产品、运营和职能日常维护",
		description: msg`通用的一页式结构，适合技术、产品、运营和职能岗位的日常版本维护。`,
		imageUrl: "/templates/jpg/onyx.jpg",
		accentColor: "rgba(35, 43, 55, 1)",
		tags: ["单栏", "通用", "一页版", "专业"],
		sidebarPosition: "none",
	},
	pikachu: {
		name: "轻量创意",
		audience: "适合内容、编辑、设计和年轻化投递",
		description: msg`保留轻量强调色，适合内容、编辑、设计和更年轻的投递场景。`,
		imageUrl: "/templates/jpg/pikachu.jpg",
		tags: ["双栏", "创意", "内容", "设计"],
		sidebarPosition: "left",
	},
	rhyhorn: {
		name: "留白设计",
		audience: "适合设计师、内容创作者和作品集简历",
		description: msg`更大留白和清爽页眉，适合设计师、内容创作者和作品集型简历。`,
		imageUrl: "/templates/jpg/rhyhorn.jpg",
		tags: ["单栏", "留白", "设计师", "作品集"],
		sidebarPosition: "none",
	},
	scizor: {
		name: "高管咨询",
		audience: "适合咨询、高管、创业公司和成果导向候选人",
		description: msg`标题强调更明确，适合咨询、高管、创业公司和需要强成果表达的候选人。`,
		imageUrl: "/templates/jpg/scizor.jpg",
		accentColor: "rgba(63, 74, 90, 1)",
		tags: ["单栏", "咨询", "管理层", "成果导向"],
		sidebarPosition: "none",
	},
} as const satisfies Record<Template, TemplateMetadata>;

export const featuredTemplateIds = [
	"collection001",
	"collection002",
	"collection003",
	"collection005",
	"collection016",
	"collection018",
	"collection021",
	"collection028",
] as const satisfies Template[];

export const primaryTemplateIds = [
	"collection001",
	"collection002",
	"collection003",
	"collection005",
	"collection007",
	"collection016",
	"collection017",
	"collection018",
	"collection019",
	"collection020",
	"collection021",
	"collection022",
	"collection024",
	"collection026",
	"collection027",
	"collection028",
	"collection029",
] as const satisfies Template[];
