import type { ResumeData } from "./data";

export const sampleResumeData: ResumeData = {
	picture: {
		hidden: true,
		url: "/photos/sample-picture.jpg",
		size: 100,
		rotation: 0,
		aspectRatio: 1,
		borderRadius: 0,
		borderColor: "rgba(0, 0, 0, 0.5)",
		borderWidth: 0,
		shadowColor: "rgba(0, 0, 0, 0.5)",
		shadowWidth: 0,
	},
	basics: {
		name: "陈嘉铭",
		headline: "前端开发工程师 | React 与工程化方向",
		email: "jiaming.chen@example.com",
		phone: "+86 138 0000 0000",
		location: "上海",
		website: {
			url: "https://jiaming.dev",
			label: "jiaming.dev",
		},
		customFields: [
			{
				id: "019bef5a-0477-77e0-968b-5d0e2ecb34e3",
				icon: "github-logo",
				text: "github.com/chenjiaming",
				link: "https://github.com/chenjiaming",
			},
			{
				id: "019bef5a-93e4-7746-ad39-3a132360f823",
				icon: "link",
				text: "juejin.cn/user/chenjiaming",
				link: "https://juejin.cn/user/chenjiaming",
			},
		],
	},
	summary: {
		title: "",
		columns: 1,
		hidden: false,
		content:
			"<p><strong>5 年前端开发经验，长期负责 B 端产品与增长业务</strong>，熟悉 React、TypeScript、组件化体系和前端工程化。能够从业务目标出发拆解需求，推动设计、后端和测试协作交付，关注页面性能、可维护性和用户体验。</p>",
	},
	sections: {
		profiles: {
			title: "",
			columns: 1,
			hidden: false,
			items: [
				{
					id: "019bef5a-93e4-7746-ad39-3d42ddc9b4d8",
					hidden: false,
					icon: "github-logo",
					iconColor: "",
					network: "GitHub",
					username: "chenjiaming",
					website: {
						url: "https://github.com/chenjiaming",
						label: "github.com/chenjiaming",
						inlineLink: false,
					},
				},
				{
					id: "019bef5a-93e4-7746-ad39-43c470b77f4a",
					hidden: false,
					icon: "link",
					iconColor: "",
					network: "掘金",
					username: "chenjiaming",
					website: {
						url: "https://juejin.cn/user/chenjiaming",
						label: "juejin.cn/user/chenjiaming",
						inlineLink: false,
					},
				},
			],
		},
		experience: {
			title: "",
			columns: 1,
			hidden: false,
			items: [
				{
					id: "019bef5a-93e4-7746-ad39-44d8cec98ca4",
					hidden: false,
					company: "字节跳动",
					position: "前端开发工程师",
					location: "上海",
					period: "2022 年 3 月 - 至今",
					website: {
						url: "",
						label: "",
						inlineLink: false,
					},
					roles: [],
					description:
						"<ul><li><p>负责内容运营后台核心模块，使用 React、TypeScript 和 TanStack Query 搭建可复用的数据录入与审核流程</p></li><li><p>主导组件抽象和表单校验规范，将同类页面开发周期缩短 35%，减少重复代码和线上回归问题</p></li><li><p>优化首屏资源加载与列表虚拟滚动，核心页面 LCP 降低 42%，千级数据滚动保持稳定</p></li><li><p>与产品、设计、后端和测试协作推进需求评审，沉淀接口契约和前端发布检查清单</p></li></ul><p></p>",
				},
			],
		},
		education: {
			title: "",
			columns: 1,
			hidden: false,
			items: [
				{
					id: "019bef5a-93e4-7746-ad39-48455f6cef9e",
					hidden: false,
					school: "上海交通大学",
					degree: "本科",
					area: "计算机科学与技术",
					grade: "GPA 3.7/4.0",
					location: "上海",
					period: "2016 - 2020",
					website: {
						url: "",
						label: "",
						inlineLink: false,
					},
					description:
						"<p>主修课程：数据结构、操作系统、计算机网络、数据库系统、软件工程、人机交互。曾参与学院 Web 实验平台建设，负责前端页面和交互实现。</p>",
				},
			],
		},
		projects: {
			title: "",
			columns: 1,
			hidden: false,
			items: [
				{
					id: "019bef5a-93e4-7746-ad39-4d2603fe2801",
					hidden: false,
					name: "企业级组件库建设",
					period: "2023 - 至今",
					website: {
						url: "https://github.com/chenjiaming/ui-kit",
						label: "查看项目",
						inlineLink: false,
					},
					description:
						"<p>参与建设面向多个业务线的 React 组件库，覆盖表单、表格、筛选器、弹窗和权限控制等高频场景。推动 Storybook 文档、单元测试和设计 Token 接入，使组件复用率和交付一致性显著提升。</p>",
				},
				{
					id: "019bef5a-93e4-7746-ad39-524195dd7eff",
					hidden: false,
					name: "简历智能优化工具",
					period: "2024",
					website: {
						url: "https://github.com/chenjiaming/resume-ai",
						label: "查看 GitHub",
						inlineLink: false,
					},
					description:
						"<p>基于简历结构化数据和岗位描述匹配，设计 JD 关键词提取、段落改写建议和版本回退能力。项目用于验证 AI 辅助简历优化流程，并沉淀为可复用的前端工作台模式。</p>",
				},
				{
					id: "019bef5a-93e4-7746-ad39-549106273c73",
					hidden: false,
					name: "低代码运营页面平台",
					period: "2021 - 2022",
					website: {
						url: "",
						label: "",
						inlineLink: false,
					},
					description:
						"<p>负责配置化页面渲染器和物料管理模块，支持运营同学快速搭建活动页。通过拖拽布局、组件参数校验和发布预览，将常规活动页面交付时间从 2 天缩短到半天。</p>",
				},
			],
		},
		skills: {
			title: "",
			columns: 1,
			hidden: false,
			items: [
				{
					id: "019bef5a-93e4-7746-ad39-5a52dcf50ed4",
					hidden: false,
					icon: "code",
					iconColor: "",
					name: "React / TypeScript",
					proficiency: "熟练",
					level: 5,
					keywords: ["Hooks", "状态管理", "组件设计"],
				},
				{
					id: "019bef5a-93e4-7746-ad39-5e8bb7cacbc8",
					hidden: false,
					icon: "brackets-curly",
					iconColor: "",
					name: "前端工程化",
					proficiency: "熟练",
					level: 4,
					keywords: ["Vite", "pnpm", "CI/CD"],
				},
				{
					id: "019bef5a-93e4-7746-ad39-622f9d41da55",
					hidden: false,
					icon: "cpu",
					iconColor: "",
					name: "数据可视化",
					proficiency: "熟练",
					level: 5,
					keywords: ["ECharts", "Canvas", "性能优化"],
				},
				{
					id: "019bef5a-93e4-7746-ad39-6574ab6814bd",
					hidden: false,
					icon: "brain",
					iconColor: "",
					name: "服务端协作",
					proficiency: "良好",
					level: 4,
					keywords: ["REST", "OpenAPI", "接口联调"],
				},
				{
					id: "019bef5a-93e4-7746-ad39-6a8e22bec684",
					hidden: false,
					icon: "shooting-star",
					iconColor: "",
					name: "用户体验",
					proficiency: "良好",
					level: 4,
					keywords: ["交互细节", "可访问性", "设计还原"],
				},
				{
					id: "019bef5a-93e4-7746-ad39-6d8bf7be7514",
					hidden: true,
					icon: "chart-line-up",
					iconColor: "",
					name: "性能优化",
					proficiency: "良好",
					level: 4,
					keywords: ["性能分析", "资源拆分", "缓存策略"],
				},
			],
		},
		languages: {
			title: "",
			columns: 1,
			hidden: false,
			items: [
				{
					id: "019bef5a-93e4-7746-ad39-73807ccc48b5",
					hidden: false,
					language: "中文",
					fluency: "母语",
					level: 5,
				},
				{
					id: "019bef5a-93e4-7746-ad39-768670459358",
					hidden: false,
					language: "英语",
					fluency: "CET-6",
					level: 4,
				},
			],
		},
		interests: {
			title: "",
			columns: 1,
			hidden: false,
			items: [
				{
					id: "019bef5a-93e4-7746-ad39-7821b4de95f7",
					hidden: false,
					icon: "game-controller",
					iconColor: "",
					name: "产品设计",
					keywords: ["业务分析", "交互体验", "用户反馈"],
				},
				{
					id: "019bef5a-93e4-7746-ad39-7c64c1a607d3",
					hidden: false,
					icon: "robot",
					iconColor: "",
					name: "AI 工具",
					keywords: ["LLM", "Prompt", "效率工具"],
				},
				{
					id: "019bef5a-93e4-7746-ad39-80bccce3c0ef",
					hidden: false,
					icon: "book-open",
					iconColor: "",
					name: "技术写作",
					keywords: ["博客", "知识沉淀", "团队分享"],
				},
				{
					id: "019bef5a-93e4-7746-ad39-84bb7e9af005",
					hidden: false,
					icon: "pen-nib",
					iconColor: "",
					name: "开源项目",
					keywords: ["工具库", "Issue 协作", "文档"],
				},
			],
		},
		awards: {
			title: "",
			columns: 1,
			hidden: false,
			items: [
				{
					id: "019bef5a-93e4-7746-ad39-8a8bb9fbe182",
					hidden: false,
					title: "年度优秀新人",
					awarder: "字节跳动",
					date: "2022 年 12 月",
					website: {
						url: "",
						label: "",
						inlineLink: false,
					},
					description: "<p>因快速承担核心业务模块并推动前端工程化规范落地，获得团队年度优秀新人奖。</p>",
				},
				{
					id: "019bef5a-93e4-7746-ad39-8dd81379c7c9",
					hidden: false,
					title: "校级优秀毕业设计",
					awarder: "上海交通大学",
					date: "2020 年 6 月",
					website: {
						url: "",
						label: "",
						inlineLink: false,
					},
					description: "<p>毕业设计聚焦低代码页面搭建平台，完成从组件协议、编辑器交互到页面渲染的完整实现。</p>",
				},
			],
		},
		certifications: {
			title: "",
			columns: 1,
			hidden: false,
			items: [
				{
					id: "019bef5a-93e4-7746-ad39-91fe8a4dfea6",
					hidden: false,
					title: "阿里云前端工程化训练营",
					issuer: "阿里云开发者社区",
					date: "2022 年 3 月",
					website: {
						url: "",
						label: "",
						inlineLink: false,
					},
					description: "",
				},
				{
					id: "019bef5a-93e4-7746-ad39-961afccc2508",
					hidden: false,
					title: "React 进阶实践认证",
					issuer: "极客时间",
					date: "2023 年 6 月",
					website: {
						url: "",
						label: "",
						inlineLink: false,
					},
					description: "",
				},
			],
		},
		publications: {
			title: "",
			columns: 1,
			hidden: false,
			items: [
				{
					id: "019bef5a-93e4-7746-ad39-9816f0081895",
					hidden: false,
					title: "大型表单系统的可维护性实践",
					publisher: "掘金",
					date: "2023 年 9 月",
					website: {
						url: "",
						label: "",
						inlineLink: false,
					},
					description: "<p>总结复杂 B 端表单在状态管理、校验、联动和可测试性方面的工程实践。</p>",
				},
				{
					id: "019bef5a-93e4-7746-ad39-9cf55c272c05",
					hidden: false,
					title: "从业务后台到组件库：前端抽象边界",
					publisher: "团队技术分享",
					date: "2024 年 5 月",
					website: {
						url: "",
						label: "",
						inlineLink: false,
					},
					description: "<p>面向团队分享组件抽象、设计 Token 和文档化流程，推动多人协作下的 UI 一致性。</p>",
				},
			],
		},
		volunteer: {
			title: "",
			columns: 2,
			hidden: false,
			items: [
				{
					id: "019bef5a-93e4-7746-ad39-a02580473e05",
					hidden: false,
					organization: "上海前端社区",
					location: "上海",
					period: "2021 - 至今",
					website: {
						url: "",
						label: "",
						inlineLink: false,
					},
					description: "<p>参与线下技术沙龙组织工作，协助准备议题、讲者沟通和现场流程，并在活动后整理技术资料。</p>",
				},
				{
					id: "019bef5a-93e4-7746-ad39-a731c5b1b286",
					hidden: false,
					organization: "高校编程辅导计划",
					location: "线上",
					period: "2020 - 2022",
					website: {
						url: "",
						label: "",
						inlineLink: false,
					},
					description: "<p>为低年级同学提供前端入门辅导，覆盖 HTML、CSS、JavaScript 和基础项目实践。</p>",
				},
			],
		},
		references: {
			title: "",
			columns: 1,
			hidden: false,
			items: [
				{
					id: "019bef5a-93e4-7746-ad39-a945c0f42dd5",
					hidden: false,
					name: "可按需提供",
					position: "",
					website: {
						url: "",
						label: "",
						inlineLink: false,
					},
					phone: "",
					description: "",
				},
			],
		},
	},
	customSections: [
		{
			title: "",
			columns: 1,
			hidden: false,
			id: "019becaf-0b87-769d-98a6-46ccf558c0e8",
			type: "experience",
			items: [
				{
					id: "019bef5a-d1fa-7289-a87c-2677688d9e75",
					hidden: false,
					company: "携程旅行",
					position: "前端开发工程师",
					location: "上海",
					period: "2020 年 6 月 - 2022 年 2 月",
					website: {
						url: "",
						label: "",
						inlineLink: false,
					},
					roles: [],
					description:
						"<ul><li>参与酒店供应链管理后台开发，负责列表检索、批量操作、权限控制和数据可视化模块</li><li>封装通用筛选器和表格操作组件，支撑 10+ 个业务页面复用</li><li>配合后端完善接口字段校验与错误提示，降低运营同学误操作成本</li><li>参与灰度发布和线上问题排查，沉淀前端监控与告警处理流程</li></ul>",
				},
				{
					id: "019bef5a-db0e-73c6-9b6e-4471703864f1",
					hidden: false,
					company: "美团",
					position: "前端实习生",
					location: "北京",
					period: "2019 年 9 月 - 2020 年 5 月",
					website: {
						url: "",
						label: "",
						inlineLink: false,
					},
					roles: [],
					description:
						"<ul><li><p>参与商家运营页面开发，完成活动配置、数据看板和表单提交等模块</p></li><li><p>使用 Vue 和 TypeScript 实现页面交互，并编写基础单元测试</p></li><li><p>根据设计稿优化移动端适配和加载状态，提升页面可读性和操作反馈</p></li></ul><p></p>",
				},
			],
		},
		{
			title: "求职信",
			columns: 1,
			hidden: false,
			id: "019bef5b-0b3d-7e2a-8a7c-12d9e23a4f6b",
			type: "cover-letter",
			items: [
				{
					id: "019bef5b-0f8d-77d1-9b2a-4a1b65e1b8aa",
					hidden: false,
					recipient:
						'<p>招聘负责人<br />某互联网公司<br />上海<br /><a href="mailto:hr@example.com">hr@example.com</a></p>',
					content:
						"<p>尊敬的招聘负责人：</p><p>您好！我希望应聘贵公司的前端开发岗位。过去几年里，我主要负责 B 端产品、组件体系和前端工程化建设，能够独立推进需求拆解、技术方案、开发联调和上线验证。</p><p>我重视业务理解、工程质量和协作效率，也乐于把复杂问题沉淀成团队可复用的方法。期待有机会进一步交流。</p><p>此致<br />陈嘉铭</p>",
				},
			],
		},
	],
	metadata: {
		template: "azurill",
		layout: {
			sidebarWidth: 30,
			pages: [
				{
					fullWidth: false,
					main: ["summary", "education", "experience"],
					sidebar: ["profiles", "skills"],
				},
				{
					fullWidth: false,
					main: ["019becaf-0b87-769d-98a6-46ccf558c0e8", "awards"],
					sidebar: ["certifications", "languages", "interests", "references"],
				},
				{
					fullWidth: true,
					main: ["projects", "publications", "volunteer"],
					sidebar: [],
				},
				{
					fullWidth: true,
					main: ["019bef5b-0b3d-7e2a-8a7c-12d9e23a4f6b"],
					sidebar: [],
				},
			],
		},
		page: {
			gapX: 12,
			gapY: 8,
			marginX: 16,
			marginY: 16,
			format: "a4",
			locale: "zh-CN",
			hideIcons: false,
		},
		design: {
			level: {
				icon: "star",
				type: "icon",
			},
			colors: {
				primary: "rgba(31, 58, 95, 1)",
				text: "rgba(0, 0, 0, 1)",
				background: "rgba(255, 255, 255, 1)",
			},
		},
		typography: {
			body: {
				fontFamily: "Noto Sans SC",
				fontWeights: ["400", "600"],
				fontSize: 10,
				lineHeight: 1.5,
			},
			heading: {
				fontFamily: "Noto Sans SC",
				fontWeights: ["500", "700"],
				fontSize: 12,
				lineHeight: 1.5,
			},
		},
		notes: "",
		styleRules: [],
	},
};
